from __future__ import annotations

import logging
import re
from pathlib import Path

import frontmatter

from src.storage.files import load_json

logger = logging.getLogger(__name__)


def _slugify(text: str) -> str:
    """Convert text to a safe filename/slug."""
    text = text.strip().lower()
    text = re.sub(r"[^\w\s-]", "", text)
    text = re.sub(r"[\s_]+", "-", text)
    return text.strip("-")


def _wikilink(title: str) -> str:
    """Create an Obsidian wikilink."""
    return f"[[{title}]]"


def generate_campaign_note(data: dict, vault_path: Path) -> Path:
    """Generate an Obsidian Markdown note for a single campaign."""
    title = data.get("title", data.get("slug", "Untitled"))
    slug = data.get("slug", _slugify(title))

    # Build YAML frontmatter
    meta = {
        "title": title,
        "brand": data.get("brand", ""),
        "agency": data.get("agency", ""),
        "country": data.get("country", ""),
        "festival": data.get("festival", ""),
        "year": data.get("year"),
        "category": data.get("category", ""),
        "award": data.get("award_level", ""),
        "techniques": data.get("techniques", []),
        "themes": data.get("themes", []),
        "tags": data.get("tags", []),
        "source_url": data.get("url", ""),
    }
    # Remove empty values from frontmatter
    meta = {k: v for k, v in meta.items() if v}

    # Build note body
    lines = []
    lines.append(f"# {title}\n")

    # Header info
    info_parts = []
    if data.get("brand"):
        info_parts.append(f"**Brand:** {data['brand']}")
    if data.get("agency"):
        info_parts.append(f"**Agency:** {data['agency']}")
    if data.get("award_level") and data.get("festival"):
        info_parts.append(f"**Award:** {data['award_level']}, {data.get('festival', '')} {data.get('year', '')}")
    if info_parts:
        lines.append(" | ".join(info_parts) + "\n")

    # Summary (Japanese first for the user, then English)
    if data.get("summary_ja"):
        lines.append("## 概要\n")
        lines.append(data["summary_ja"] + "\n")
    if data.get("summary"):
        lines.append("## Summary\n")
        lines.append(data["summary"] + "\n")

    # Key Insight
    if data.get("key_insight_ja") or data.get("key_insight"):
        lines.append("## Key Insight\n")
        if data.get("key_insight_ja"):
            lines.append(data["key_insight_ja"] + "\n")
        if data.get("key_insight"):
            lines.append(f"*{data['key_insight']}*\n")

    # Techniques
    if data.get("techniques"):
        lines.append("## Techniques\n")
        for tech in data["techniques"]:
            lines.append(f"- {_wikilink(tech)}")
        lines.append("")

    # Themes
    if data.get("themes"):
        lines.append("## Themes\n")
        for theme in data["themes"]:
            lines.append(f"- {_wikilink(theme)}")
        lines.append("")

    # Description
    if data.get("description"):
        lines.append("## Description\n")
        lines.append(data["description"] + "\n")

    # Case Study
    if data.get("case_study_text"):
        lines.append("## Case Study\n")
        lines.append(data["case_study_text"] + "\n")

    # Target Audience
    if data.get("target_audience"):
        lines.append("## Target Audience\n")
        lines.append(data["target_audience"] + "\n")

    # Media Channels
    if data.get("media_channels"):
        lines.append("## Media Channels\n")
        for ch in data["media_channels"]:
            lines.append(f"- {ch}")
        lines.append("")

    # Effectiveness
    if data.get("effectiveness_notes"):
        lines.append("## Effectiveness\n")
        lines.append(data["effectiveness_notes"] + "\n")

    # Media links
    if data.get("video_urls") or data.get("image_urls"):
        lines.append("## Media\n")
        for v in data.get("video_urls", []):
            lines.append(f"- [Video]({v})")
        for img in data.get("image_urls", []):
            lines.append(f"- ![]({img})")
        lines.append("")

    # Credits
    if data.get("credits"):
        lines.append("## Credits\n")
        lines.append("| Role | Name |")
        lines.append("|------|------|")
        for c in data["credits"]:
            lines.append(f"| {c.get('role', '')} | {c.get('name', '')} |")
        lines.append("")

    # Festival link
    if data.get("festival") and data.get("year"):
        lines.append("## Festival\n")
        festival_year = f"{data['festival']} {data['year']}"
        lines.append(f"- {_wikilink(festival_year)}\n")

    # Source
    if data.get("url"):
        lines.append(f"---\n*Source: [{data['url']}]({data['url']})*\n")
    lines.append("*Generated by Idea Distillery*\n")

    # Write file
    content = "\n".join(lines)
    post = frontmatter.Post(content, **meta)
    out_dir = vault_path / "campaigns"
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / f"{slug}.md"
    out_path.write_text(frontmatter.dumps(post), encoding="utf-8")

    logger.info(f"Exported: {out_path}")
    return out_path
